### ISSUE TITLE
Shape Checker throws an NPE

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-specs#126]
For the following config:

```
build/install/ShapeChecker/bin/ShapeChecker \
-v ../../specs/cm/change-mgt-vocab.ttl \
-v ../../specs/cm/change-mgt-shapes.ttl
```

I get the following exception:

```
Exception in thread "main" java.lang.NullPointerException
	at net.open_services.scheck.shapechecker.ResultModelProcessor.processResults(ResultModelProcessor.java:54)
	at net.open_services.scheck.shapechecker.IssueSummarizer.countIssues(IssueSummarizer.java:45)
	at net.open_services.scheck.shapechecker.ResultModel.summarizeIssues(ResultModel.java:268)
```

**Comment by berezovskyi** [comment]
Works fine with `-v ../../specs/cm/change-mgt-shapes.ttl` alone.

**Comment by berezovskyi** [comment]
🤦‍♂ 🤦‍♂ 🤦‍♂ 

Turns out I was trying to run vocab checks on a shapes file! Still, I think we should fix it to return an error instead of failing with an NPE.

**Comment by ndjc** [comment]
I have a tentative fix, but it is not architecturally sound yet - won't submit this week.

**Comment by berezovskyi** [comment]
no worries, I merely closed it by accident

**Comment by berezovskyi** [comment]
Assuming @ndjc intended to close this via #371.
